In [1]:
import timeit
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
import warnings
%matplotlib inline
warnings.filterwarnings('ignore')

In [2]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

import io

dataset = pd.read_csv('/content/drive/MyDrive/creditcard_1.csv')

Mounted at /content/drive


In [3]:
print(dataset.shape)

(2001, 31)


In [4]:
#split dataset in features and target variable
X = dataset.drop('Class', axis=1) # Features
y = dataset['Class'] # Target variable

In [5]:
# Split dataset into training set and test set
train_x, test_x, train_Y, test_Y = train_test_split(X, y, test_size=0.3, random_state=1)

In [6]:
# Check the shape of all of these
print("X_train shape is : ", train_x.shape)
print("X_test shape  is : ", test_x.shape)
print("y_train shape is : ", train_Y.shape)
print("y_test shape is  : ", test_Y.shape)

X_train shape is :  (1400, 30)
X_test shape  is :  (601, 30)
y_train shape is :  (1400,)
y_test shape is  :  (601,)


In [7]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf.fit(train_x, train_Y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='lbfgs')

In [8]:
y_pred = clf.predict(test_x)

In [9]:
confusion_matrix = metrics.confusion_matrix(test_Y, y_pred)
confusion_matrix

array([[447,   0],
       [154,   0]])

In [10]:
print(classification_report(test_Y,y_pred))

              precision    recall  f1-score   support

           0       0.74      1.00      0.85       447
           1       0.00      0.00      0.00       154

    accuracy                           0.74       601
   macro avg       0.37      0.50      0.43       601
weighted avg       0.55      0.74      0.63       601



In [11]:
roc_auc_score(test_Y, clf.predict_proba(test_x)[:, 1])

0.5

In [12]:
clf1 = MLPClassifier(solver='sgd',shuffle=True, alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=1)
clf1.fit(train_x, train_Y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=1,
              solver='sgd')

In [13]:
y_pred1 = clf1.predict(test_x)

In [14]:
confusion_matrix1 = metrics.confusion_matrix(test_Y, y_pred)
confusion_matrix1


array([[447,   0],
       [154,   0]])

In [15]:
print(classification_report(test_Y,y_pred1))

              precision    recall  f1-score   support

           0       0.74      1.00      0.85       447
           1       0.00      0.00      0.00       154

    accuracy                           0.74       601
   macro avg       0.37      0.50      0.43       601
weighted avg       0.55      0.74      0.63       601



In [17]:
print("Accuracy:",metrics.accuracy_score(test_Y, y_pred1))
print("Precision:",metrics.precision_score(test_Y, y_pred1))
print("Recall:",metrics.recall_score(test_Y, y_pred1))
print("F1_score:",metrics.f1_score(test_Y, y_pred1))
print("ROC_AUC Score:",roc_auc_score(test_Y, clf1.predict_proba(test_x)[:, 1]))

Accuracy: 0.7437603993344426
Precision: 0.0
Recall: 0.0
F1_score: 0.0
ROC_AUC Score: 0.5055928411633109


In [18]:
clf2 = MLPClassifier(solver='adam',shuffle=True, alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=5)
clf2.fit(train_x, train_Y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=5)

In [19]:
y_pred2 = clf2.predict(test_x)

In [20]:
confusion_matrix2 = metrics.confusion_matrix(test_Y, y_pred)

confusion_matrix2

array([[447,   0],
       [154,   0]])

In [23]:
print(classification_report(test_Y,y_pred2))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97       447
           1       0.96      0.87      0.91       154

    accuracy                           0.96       601
   macro avg       0.96      0.93      0.94       601
weighted avg       0.96      0.96      0.96       601



In [22]:
print("Accuracy:",metrics.accuracy_score(test_Y, y_pred2))
print("Precision:",metrics.precision_score(test_Y, y_pred2))
print("Recall:",metrics.recall_score(test_Y, y_pred2))
print("F1_score:",metrics.f1_score(test_Y, y_pred2))
print("ROC_AUC Score:",roc_auc_score(test_Y, clf2.predict_proba(test_x)[:, 1]))

Accuracy: 0.9584026622296173
Precision: 0.9640287769784173
Recall: 0.8701298701298701
F1_score: 0.9146757679180887
ROC_AUC Score: 0.979124901943694


In [ ]:
clf3 = MLPClassifier(solver='sgd',shuffle=True,learning_rate='constant', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=5)
clf3.fit(train_x, train_Y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2), random_state=5,
              solver='sgd')

In [ ]:
y_pred3 = clf3.predict(test_x)

In [ ]:
confusion_matrix3 = metrics.confusion_matrix(test_Y, y_pred)
confusion_matrix3

array([[447,   0],
       [154,   0]])

In [24]:
clf4 = MLPClassifier(solver='sgd',shuffle=True,learning_rate='invscaling', alpha=1e-5,hidden_layer_sizes=(5, 2), random_state=5)
clf4.fit(train_x, train_Y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(5, 2),
              learning_rate='invscaling', random_state=5, solver='sgd')

In [25]:
y_pred4 = clf4.predict(test_x)

In [29]:
confusion_matrix4 = metrics.confusion_matrix(test_Y, y_pred4)
confusion_matrix4

array([[  0, 447],
       [  0, 154]])

In [30]:

print("Accuracy:",metrics.accuracy_score(test_Y, y_pred4))
print("Precision:",metrics.precision_score(test_Y, y_pred4))
print("Recall:",metrics.recall_score(test_Y, y_pred4))
print("F1_score:",metrics.f1_score(test_Y, y_pred4))
print("ROC_AUC Score:",roc_auc_score(test_Y, clf4.predict_proba(test_x)[:, 1]))

Accuracy: 0.2562396006655574
Precision: 0.2562396006655574
Recall: 1.0
F1_score: 0.40794701986754967
ROC_AUC Score: 0.5


In [31]:
clf5 = MLPClassifier(solver='adam',shuffle=True, alpha=1e-5,hidden_layer_sizes=(10, 4), random_state=5)
clf5.fit(train_x, train_Y)

MLPClassifier(alpha=1e-05, hidden_layer_sizes=(10, 4), random_state=5)

In [32]:
y_pred5 = clf5.predict(test_x)

In [33]:
print("Accuracy:",metrics.accuracy_score(test_Y, y_pred5))
print("Precision:",metrics.precision_score(test_Y, y_pred5))
print("Recall:",metrics.recall_score(test_Y, y_pred5))
print("F1_score:",metrics.f1_score(test_Y, y_pred5))
print("ROC_AUC Score:",roc_auc_score(test_Y, clf5.predict_proba(test_x)[:, 1]))

Accuracy: 0.9633943427620633
Precision: 0.9782608695652174
Recall: 0.8766233766233766
F1_score: 0.9246575342465754
ROC_AUC Score: 0.9857636770388448
